[workspace]
members = [
    "crates/event_model",
    "crates/event_router",
    "crates/pokemon_box",
    "crates/pokemon-model",
]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
debug = false