[package]
name = "event-model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.1"
ic-cdk = "0.5.2"
ic-types = "0.4.2"
serde = "1.0.144"
